{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"EPOS\",\"Sales\",\"Sheet1\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.118.621.0 (23.06)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "6fbd4f11-9b68-42bc-bccb-420756084c76",
        "fromColumn": "Date of Sale",
        "fromTable": "EPOS",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_1f7fef84-6cb6-4837-ac4d-9a2f1bf13403"
      },
      {
        "name": "b1c6c037-e55c-4fb4-ba15-5aa2043f1794",
        "fromColumn": "Date of qty",
        "fromTable": "EPOS",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ff370025-a293-4e99-ab37-9e7f71c2175b"
      },
      {
        "name": "91dab3d0-8e74-4ec0-afb3-00ce4c173a81",
        "fromColumn": "Date",
        "fromTable": "Sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_46dcce9a-30e6-464f-a2b6-64014fc5cce8"
      },
      {
        "name": "2f23f2e6-9e03-4aa9-97b0-f12f49af001e",
        "fromColumn": "Date",
        "fromTable": "Table",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7ae0e58c-615f-475a-bd67-59cf80bcf04d"
      },
      {
        "name": "b36c78b6-584e-4823-af9b-1381cf5ad285",
        "fromColumn": "OrderDate",
        "fromTable": "Sheet1",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ef518d95-e400-4eb0-adfb-9d5212a0b89e"
      },
      {
        "name": "a68d64c0-e2f5-4f39-b7e6-ce67333a023b",
        "fromColumn": "StockDate",
        "fromTable": "Sheet1",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7b50c5f9-562b-4c94-a2c0-93c56d271e78"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_0c9a4c37-05ac-42ec-875e-c1ff0eeede86",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1150e7a2-b2cc-4ff5-bd92-e7b6f5a3e68e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "91be0452-c1fb-4ded-9774-ed79b18ecc81",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7c1f3203-46cd-4f06-a578-6691c9868739",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e8a84caf-928d-489a-b2b6-790d2b10d127",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5f032726-9e43-4b36-b576-cfcacf50c98d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9ddce1cd-65a3-4bdb-8609-03c2e0641bed",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6003abc3-f056-483f-8363-d74d49ffb80c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6c314e43-dc7b-4e0c-8125-fff233083030",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5ab3c033-d0b5-4314-b750-171d10ef975a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e19190c5-3395-4a98-bd73-5997aa0a81f3",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c0947a5a-ee3e-4c77-8a65-69f88979363b",
                "ordinal": 3
              }
            ],
            "lineageTag": "7c67ad1e-c863-4b14-918f-3869c23de60e"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "c7edba24-6fc1-4338-b028-5afe12f7e343",
        "partitions": [
          {
            "name": "DateTableTemplate_0c9a4c37-05ac-42ec-875e-c1ff0eeede86-84b84748-8a9a-4f4d-b553-d8f8d21d405d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "EPOS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "Brands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3193555e-8104-4620-ba5e-37a127a5e0c7",
            "sourceColumn": "Brands",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "caec6feb-e550-4532-8d4d-f24f496a60f8",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba4744ff-09c9-4fe2-acd5-cafe3565b081",
            "sourceColumn": "Customer",
            "summarizeBy": "none"
          },
          {
            "name": "Date of Sale",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5610209d-63c1-4cda-b5a3-e8643f86b555",
            "sourceColumn": "Date of Sale",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_1f7fef84-6cb6-4837-ac4d-9a2f1bf13403"
                },
                "isDefault": true,
                "relationship": "6fbd4f11-9b68-42bc-bccb-420756084c76"
              }
            ]
          },
          {
            "name": "Date of qty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e8544bf8-09ae-4b29-aa72-d64627f049c4",
            "sourceColumn": "Date of qty",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_ff370025-a293-4e99-ab37-9e7f71c2175b"
                },
                "isDefault": true,
                "relationship": "b1c6c037-e55c-4fb4-ba15-5aa2043f1794"
              }
            ]
          },
          {
            "name": "Manufacturer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eae8b6fc-c1d4-4b25-b406-b04df057aa3e",
            "sourceColumn": "Manufacturer",
            "summarizeBy": "none"
          },
          {
            "name": "Promoter Store Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39a47187-b3df-4061-b9c8-0c7f63e5416f",
            "sourceColumn": "Promoter Store Name",
            "summarizeBy": "none"
          },
          {
            "name": "Qty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0e428063-895e-415a-b3ba-06fe896fafca",
            "sourceColumn": "Qty",
            "summarizeBy": "sum"
          },
          {
            "name": "Sale Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fc1048ca-af3e-464e-a651-084715f48a59",
            "sourceColumn": "Sale Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Sale Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "106a5e98-9a50-44bf-8399-3e888fb489c3",
            "sourceColumn": "Sale Type",
            "summarizeBy": "none"
          },
          {
            "name": "Store Format",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ce0e0ea-4ccc-4c5f-aa6d-f4969003a947",
            "sourceColumn": "Store Format",
            "summarizeBy": "none"
          },
          {
            "name": "Store Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2790cb93-d490-412d-9e49-89aab7c67f09",
            "sourceColumn": "Store Name",
            "summarizeBy": "none"
          },
          {
            "name": "StoreName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1e9285d-4716-47ff-89a7-83f93336a2e9",
            "sourceColumn": "StoreName",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(EPOS[Date of Sale],\"yyyy\")",
            "isDataTypeInferred": true,
            "lineageTag": "71932385-10a3-4629-b5e1-213192ba8ccb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "cf315096-3545-4a13-84f1-9ed8acdee928",
        "measures": [
          {
            "name": "Others Sale Amount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM('EPOS'[Sale Amount]),FILTER('EPOS','EPOS'[Brands]<>\"Unilever\"&&'EPOS'[Brands]<>\"Unilever UI\"))",
            "lineageTag": "ac980aa6-76fa-4b8f-8054-997214fd59ca"
          },
          {
            "name": "Unilever Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM('EPOS'[Sale Amount]),'EPOS'[Brands]=\"Unilever\" || 'EPOS'[Brands]= \"Unilever UI\")",
            "lineageTag": "7d1adf67-7268-4c73-8fcd-5c923428b27b"
          },
          {
            "name": "Sum of sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(EPOS[Sale Amount]))",
            "lineageTag": "71013483-fd21-4365-828f-d1735890d602"
          },
          {
            "name": "Average Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(EPOS[Sale Amount])",
            "lineageTag": "b99b544f-0148-4abe-a934-8364748fedf3"
          },
          {
            "name": "Average Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGEX(EPOS,EPOS[Sale Amount]*EPOS[Qty])",
            "lineageTag": "dc71ff04-d466-479f-a448-57350894174d"
          },
          {
            "name": "count",
            "expression": "COUNT(EPOS[Brands])",
            "formatString": "0",
            "lineageTag": "541c3906-4a5e-4476-bfa4-2975b5d53646"
          },
          {
            "name": "countrows",
            "expression": "COUNTROWS(EPOS)",
            "formatString": "0",
            "lineageTag": "b521ed6c-f2a6-48ac-accc-d25c5d17f4a8"
          },
          {
            "name": "Sum of profit",
            "expression": [
              "SUMX(Sales,",
              "                            Sales[SalesAmount]-Sales[ProductCost])"
            ],
            "formatString": "0",
            "lineageTag": "0008cf5a-e282-4d78-ae85-d1f5d3191584"
          }
        ],
        "partitions": [
          {
            "name": "EPOS-6acbd5af-b275-4690-9c6c-bb8c2328a556",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Admin\\Downloads\\Working EPOS Data.xlsx\"), null, true),",
                "    #\"EPOS Main_Sheet\" = Source{[Item=\"EPOS Main\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"EPOS Main_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Promoter Store Name\", type text}, {\"Customer\", type text}, {\"StoreName\", type text}, {\"Category\", type text}, {\"Sale Type\", type text}, {\"Brands\", type text}, {\"Manufacturer\", type text}, {\"Store Format\", type text}, {\"Store Name\", type text}, {\"Date of Sale\", type date}, {\"Sale Amount\", type number}, {\"Date of qty\", type date}, {\"Qty\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_1f7fef84-6cb6-4837-ac4d-9a2f1bf13403",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "89533664-9080-483e-9391-e91f9aae8e42",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "acb20241-39be-4180-9490-f3b2f6022733",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e545641f-1f4d-4a5f-b17d-0f095366cd2c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "566b7c39-9225-4c42-b0f9-6d82939f3b15",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "246abe37-729b-436e-96e8-9ef2174c1d23",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e3c9e0a2-f495-4529-994a-01ed7dacfb08",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "74cb3345-62a0-468e-8a51-d2c1b89c7a8c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4ade3589-c39e-4131-9747-1344b41e51d2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "61655774-c72b-4c50-afba-553c24ea2741",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8b877c74-4372-4bf6-bcb3-ab3690bf7480",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "047f140c-dd74-43e1-8d43-b66819591959",
                "ordinal": 3
              }
            ],
            "lineageTag": "444acf87-8f01-4623-ac7e-b2c26298fe9d"
          }
        ],
        "isHidden": true,
        "lineageTag": "15cfd459-3fd6-4f5c-b460-eb230a6edfb8",
        "partitions": [
          {
            "name": "LocalDateTable_1f7fef84-6cb6-4837-ac4d-9a2f1bf13403-98cb2dee-a7ca-4ec9-8e7f-7869d4034162",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('EPOS'[Date of Sale])), 1, 1), Date(Year(MAX('EPOS'[Date of Sale])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_46dcce9a-30e6-464f-a2b6-64014fc5cce8",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5f9e22fb-8f20-4ba4-a723-e897bfbe32ec",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d04e37c7-00e2-45c2-ab03-5ddb67e2db64",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2cd1f7e0-53d5-4a1f-a845-83b43dcc6e4c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "dbe3c87c-6f76-4f8a-943a-7517a7171861",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e91a2800-461a-44c4-a076-5a86d091b066",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3dfc2146-a3d9-44e8-86d5-c738cc1d7d94",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "39d1c1b0-3330-47c5-928f-3c4178a9cb3a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c21ddbb4-eac0-45cc-b04f-c4e5a56728e6",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b52d5dad-74bc-4aa2-89ca-4b3e03c375f0",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "21550a75-751c-4d27-a2b3-8615d0bd2316",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ee814f15-89c2-4cce-96bd-589c8de2b471",
                "ordinal": 3
              }
            ],
            "lineageTag": "0d15961c-9853-4702-8bb3-06b7a0163849"
          }
        ],
        "isHidden": true,
        "lineageTag": "4427d799-c085-41d1-86ce-0a0f0eb273a1",
        "partitions": [
          {
            "name": "LocalDateTable_46dcce9a-30e6-464f-a2b6-64014fc5cce8-e1e38251-0592-46b8-a72a-1a83dd0bace5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Sales'[Date])), 1, 1), Date(Year(MAX('Sales'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_7ae0e58c-615f-475a-bd67-59cf80bcf04d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "84fb4e75-b741-4bb2-90e1-ba1d6e5556ab",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0592ef7c-99de-4041-8eeb-59e2609589b0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bce6a759-a953-4e07-b01b-ef6b7f530ab9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "28d8e65b-d274-47fc-883b-b3edf3d1d60c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a0c68a77-c5c7-46f8-a26b-24fde2eb6bd6",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4feb4c86-5519-4516-bc55-b3e5fd3a6ace",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2d0fa2ca-2bce-4c3e-a946-253b6202a9b2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b3671359-08bf-4e62-95cb-c2715fdaf987",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2b65eb5f-c02c-498a-8e62-9d72a10d68e0",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f6a94438-246f-4ed3-aad8-c2207e71ed27",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2a5a0f81-8018-43ff-988f-d3f6283e2bb1",
                "ordinal": 3
              }
            ],
            "lineageTag": "6a7a7900-31b1-49e4-89ff-16e21ea36f63"
          }
        ],
        "isHidden": true,
        "lineageTag": "b0ffa288-bf2c-4584-83e5-c52368d9eceb",
        "partitions": [
          {
            "name": "LocalDateTable_7ae0e58c-615f-475a-bd67-59cf80bcf04d-cc33e801-e589-43d7-b646-ec657790c036",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Table'[Date])), 1, 1), Date(Year(MAX('Table'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_7b50c5f9-562b-4c94-a2c0-93c56d271e78",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "fcb63037-9528-418c-bd22-a7fbea472502",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bba2ed6e-7b33-4087-b405-84ab437c9ede",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8c6e969d-929f-4240-bbee-b1a4b573553b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4a39d944-48d1-40a2-b61d-b73dde565333",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "65959ead-22c1-406a-a411-86182f9c8a3d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d4604cf8-4dcb-4c92-8662-e025b08ae13d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "82d03f2a-94e2-4e8d-b92b-5664c124321a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "bd5f5bf3-6a8a-4d9a-b545-2ba2f8fa73c2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "db126c42-d417-4cf6-a43b-cb06ded18b72",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b0ff1830-05e0-4407-9f36-e49cda69a844",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3d418250-0f4a-4500-9580-e452ef5d245c",
                "ordinal": 3
              }
            ],
            "lineageTag": "a2f663b2-3763-48cb-838d-2888f5828a73"
          }
        ],
        "isHidden": true,
        "lineageTag": "04ccaf9b-a5a7-4a6f-b831-dc34f0d59aaa",
        "partitions": [
          {
            "name": "LocalDateTable_7b50c5f9-562b-4c94-a2c0-93c56d271e78-31411b36-c96b-40b2-8733-3b5265b4e93a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Sheet1'[StockDate])), 1, 1), Date(Year(MAX('Sheet1'[StockDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_ef518d95-e400-4eb0-adfb-9d5212a0b89e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6963978c-bb80-442d-8ac9-623416d1f134",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "99ec262b-32e7-4506-9eb9-9c23ed7840a3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9c79cc21-3aa0-457e-a3eb-848fda15c8cd",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "348d6739-3330-415a-bc85-4a05a5806375",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "00b063db-5505-419f-ab6f-f8bf72496bec",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3416bb7c-7833-4454-af26-74cff664934f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8efb7055-b2b8-4012-9a2e-e3f2127e642c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ad3ffdf9-e9ff-474a-b388-c326bc5a52ea",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3dece384-9488-4b4d-aa4d-56dc3ddcc503",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8ab4aef8-3553-4f7a-ac1e-af903b7f6010",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7965d19d-2544-411a-a9ad-d0b4d3ea68ae",
                "ordinal": 3
              }
            ],
            "lineageTag": "94a9ad84-5d35-4b2d-bccd-f1084f91414d"
          }
        ],
        "isHidden": true,
        "lineageTag": "e4b2f3cc-4011-4594-a3e5-377a69151ebe",
        "partitions": [
          {
            "name": "LocalDateTable_ef518d95-e400-4eb0-adfb-9d5212a0b89e-bc68d560-9a45-4a57-8566-563af23f6b18",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Sheet1'[OrderDate])), 1, 1), Date(Year(MAX('Sheet1'[OrderDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_ff370025-a293-4e99-ab37-9e7f71c2175b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1f79874c-a772-4483-bb1a-e6aa72f2055d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0bba2533-1595-4c2a-8aab-1dd0131903c4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1cf714e7-f2b3-41b1-ad0c-6f29338a70d8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5cd3ed08-9024-4062-80e0-3945fb5fac00",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7ba95001-70ca-41f1-9a08-2b728cb7d1d6",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1c62750b-4616-4816-8af0-43470cb2d949",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "063c798e-d7a0-427b-8e73-d54695d0fa3f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5b6af46e-3bd6-4f29-b6c5-fb517c0b0251",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "84335df5-61f3-4fc9-96cf-014179cc6c1c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "7e1c1618-a87b-446b-a2ae-9be6f5f8bb4f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c0696d10-7ace-4dcb-bf08-4847662a3c56",
                "ordinal": 3
              }
            ],
            "lineageTag": "b684519a-10c3-41a0-b64b-ad75e536ba6f"
          }
        ],
        "isHidden": true,
        "lineageTag": "8ccb61eb-2854-4e6d-8885-53881b6cd88c",
        "partitions": [
          {
            "name": "LocalDateTable_ff370025-a293-4e99-ab37-9e7f71c2175b-0f923990-77ba-4fc9-a432-46b3876863f2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('EPOS'[Date of qty])), 1, 1), Date(Year(MAX('EPOS'[Date of qty])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1d99538-ef6e-4ead-a4b2-262f4255d70f",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c9a9f08a-2e63-4ebc-acf6-d2cf92f670c9",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_46dcce9a-30e6-464f-a2b6-64014fc5cce8"
                },
                "isDefault": true,
                "relationship": "91dab3d0-8e74-4ec0-afb3-00ce4c173a81"
              }
            ]
          },
          {
            "name": "OrderID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "431adee2-6f4e-4f6b-b7b0-cf3de1634c93",
            "sourceColumn": "OrderID",
            "summarizeBy": "count"
          },
          {
            "name": "Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ed0d3522-94ba-4c72-80e9-bc9d87491a6f",
            "sourceColumn": "Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c2f82ca-9efc-434c-a89f-1faabc43b9a0",
            "sourceColumn": "Product",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c35e3444-0fee-4ff5-ac4d-e219b3e793cf",
            "sourceColumn": "ProductCost",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5ae6a12f-0b86-4be8-afe8-e4f1cb87db03",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9498a70b-a29e-494a-befe-2505c149d806",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "SalesAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "433772a4-79c1-43bd-b5ed-b6f3dc0082cf",
            "sourceColumn": "SalesAmount",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "ed5cbf07-4ef2-44de-90d9-665dc5bc935b",
        "measures": [
          {
            "name": "furniture",
            "expression": "CALCULATE(SUM(Sales[SalesAmount]),Sales[Category]=\"Furniture\")",
            "formatString": "0",
            "lineageTag": "a2b96dd0-bce3-4579-b78d-0357e2c8c6c1"
          },
          {
            "name": "All function",
            "expression": "SUMX(ALL(Sales),Sales[SalesAmount])",
            "formatString": "0",
            "lineageTag": "bdba704b-9181-4919-9397-d4ad494dd205"
          },
          {
            "name": "Profit",
            "expression": "SUMX(Sales,Sales[SalesAmount]-Sales[ProductCost])",
            "formatString": "0",
            "lineageTag": "1df6fccb-981c-4637-831e-c499ec60f486"
          },
          {
            "name": "All Profit",
            "expression": "SUMX(ALL(Sales),Sales[SalesAmount]-Sales[ProductCost])",
            "formatString": "0",
            "lineageTag": "d7554d4a-0bfa-4ec0-b203-6b8786d36d01"
          },
          {
            "name": "sales 1",
            "expression": "SUM(Sales[SalesAmount])",
            "formatString": "0",
            "lineageTag": "4f75e140-6b7a-4e67-b93b-9e8eef55db1e"
          },
          {
            "name": "Total Sales",
            "expression": "SUMX(ALL(Sales),Sales[SalesAmount])",
            "formatString": "0",
            "lineageTag": "b77bd7d6-8c51-41a8-980c-625e8028176f"
          },
          {
            "name": "All except",
            "expression": "CALCULATE(SUM(Sales[SalesAmount]),ALLEXCEPT(Sales,Sales[Product]))",
            "formatString": "0",
            "lineageTag": "95cd6a59-2a8b-4cf2-b970-a71bcecd205b"
          },
          {
            "name": "Allselected",
            "expression": "CALCULATE(SUM(Sales[SalesAmount]),ALLSELECTED(Sales[Product]))",
            "formatString": "0",
            "lineageTag": "073e1feb-9fd7-4206-82dd-9596650e0cdb"
          }
        ],
        "partitions": [
          {
            "name": "Sales-4d91f29f-a633-4b4f-aa3d-153ffc7a72ff",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Admin\\Downloads\\Filter Dax Dataset.xlsx\"), null, true),",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"OrderID\", Int64.Type}, {\"Product\", type text}, {\"Category\", type text}, {\"Quantity\", Int64.Type}, {\"Price\", Int64.Type}, {\"Date\", type date}, {\"Region\", type text}, {\"SalesAmount\", Int64.Type}, {\"ProductCost\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sheet1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cbc688d5-b4ec-4161-9bf8-62f33995e033",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "count"
          },
          {
            "name": "OrderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "fdc3c6f9-d7ff-410d-8e61-85112c610fc6",
            "sourceColumn": "OrderDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_ef518d95-e400-4eb0-adfb-9d5212a0b89e"
                },
                "isDefault": true,
                "relationship": "b36c78b6-584e-4823-af9b-1381cf5ad285"
              }
            ]
          },
          {
            "name": "OrderLineItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0a49703b-dc63-48f3-8676-cc8d7e6d1d9d",
            "sourceColumn": "OrderLineItem",
            "summarizeBy": "sum"
          },
          {
            "name": "OrderNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8362c50c-19f2-4c09-b9c3-a758e3df06e3",
            "sourceColumn": "OrderNumber",
            "summarizeBy": "none"
          },
          {
            "name": "OrderQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b6e95ce9-9431-45f7-8c38-5749c2d35cb9",
            "sourceColumn": "OrderQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "97f5f3cf-0b2f-4fa6-9205-00830a7a713c",
            "sourceColumn": "ProductKey",
            "summarizeBy": "count"
          },
          {
            "name": "QuantityType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4445721-83b5-433b-83c6-b950fa394151",
            "sourceColumn": "QuantityType",
            "summarizeBy": "none"
          },
          {
            "name": "StockDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "13d40953-a6bb-43f8-91e9-4f206bd8bea6",
            "sourceColumn": "StockDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_7b50c5f9-562b-4c94-a2c0-93c56d271e78"
                },
                "isDefault": true,
                "relationship": "a68d64c0-e2f5-4f39-b7e6-ce67333a023b"
              }
            ]
          },
          {
            "name": "TerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "89c02d55-54e2-4da5-8122-3866ece8049e",
            "sourceColumn": "TerritoryKey",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "6ff3f016-a314-4145-bdd3-1ea4acf2c84a",
        "measures": [
          {
            "name": "MTD",
            "expression": "TOTALMTD(SUM(Sheet1[OrderQuantity]),Sheet1[OrderDate].[Date])",
            "formatString": "0",
            "lineageTag": "df9c9877-c372-421c-853b-e77862e8656a"
          },
          {
            "name": "YTD",
            "expression": "TOTALYTD(SUM(Sheet1[OrderQuantity]),Sheet1[OrderDate].[Date])",
            "formatString": "0",
            "lineageTag": "6875cbec-e2f5-4648-89ed-71c869c8d385"
          }
        ],
        "partitions": [
          {
            "name": "Sheet1-9903de35-ef93-42d9-bd83-677878ef472c",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Admin\\Downloads\\Sales Dataset.xlsx\"), null, true),",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"OrderDate\", type date}, {\"StockDate\", type date}, {\"OrderNumber\", type text}, {\"ProductKey\", Int64.Type}, {\"CustomerKey\", Int64.Type}, {\"TerritoryKey\", Int64.Type}, {\"OrderLineItem\", Int64.Type}, {\"OrderQuantity\", Int64.Type}, {\"QuantityType\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Table",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "7b6d2ea447a94ca9b73fa13843c5aee6"
          }
        ],
        "columns": [
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f870b557-9655-4790-84a4-cbfded6a577a",
            "sourceColumn": "Sales[Category]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b3de4759-7eee-4c81-94b7-f5dc9b745ccc",
            "sourceColumn": "Sales[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_7ae0e58c-615f-475a-bd67-59cf80bcf04d"
                },
                "isDefault": true,
                "relationship": "2f23f2e6-9e03-4aa9-97b0-f12f49af001e"
              }
            ]
          },
          {
            "name": "OrderID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5fb33734-b051-4f38-a380-1b0005d61019",
            "sourceColumn": "Sales[OrderID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f3eaa8f7-32c3-4eba-b58f-98290febf093",
            "sourceColumn": "Sales[Price]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "24c0e770-6bfc-4816-bc7e-69259d01a3ff",
            "sourceColumn": "Sales[Product]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ProductCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "54364a28-5d44-43f8-b36d-0086e925789a",
            "sourceColumn": "Sales[ProductCost]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e1529e8a-5716-47bc-a52d-715a4af7411a",
            "sourceColumn": "Sales[Quantity]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "92a18fc7-bf1a-4a09-96b5-f74134ddfb55",
            "sourceColumn": "Sales[Region]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SalesAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a111d80c-5d3d-4d31-942c-a6bbf2314b27",
            "sourceColumn": "Sales[SalesAmount]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "a48eeef4-dfb7-4ec3-8fac-53c9d1d81360",
        "partitions": [
          {
            "name": "Table-c00ba0bb-c543-4b96-8b03-b2c2afee5a0b",
            "mode": "import",
            "source": {
              "expression": "ALL(Sales)",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}